Update procedures descriptions and modes according to the test results
neo4j/docs-operations pull request #1155
Opened 2023-10-24 13:57 UTC by NataliaIvakina

2023-10-24 13:59 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates.

You can view the updated docs at https://neo4j-docs-operations-1155.surge.sh
<!-- Sticky Pull Request Comment -->

2023-10-26 17:00 UTC, renetapopova commented
I started reviewing the PR, and I noticed that some of the descriptions in the docs had been improved, so we might consider improving the descriptions in the code base instead. Also, some of the mismatches are related to roles and labels. We should decide if we want to uncomment them or skip the slashes in the test. I'll leave it for now, and we can look into it together.

2023-11-10 11:09 UTC, renetapopova commented on modules/ROOT/pages/reference/procedures.adoc
> +| label:admin-only[] New in 5.0.
```suggestion
| label:new[Introduced in 5.0]  label:admin-only[]
```

2023-11-10 11:40 UTC, renetapopova requested changes

2023-11-10 11:40 UTC, renetapopova commented on modules/ROOT/pages/reference/procedures.adoc
> +Query the given full-text index. Returns the matching nodes, and their Lucene query score, ordered by score.
Let's see if we can update the code base instead. You can remove it for now.

2023-11-10 11:40 UTC, renetapopova commented on modules/ROOT/pages/reference/procedures.adoc
> +Query the given full-text index. Returns the matching relationships, and their Lucene query score, ordered by score.
the same here

2023-11-10 11:40 UTC, renetapopova commented on modules/ROOT/pages/reference/procedures.adoc
> +Create a named node vector index for the given label and property for a specified vector dimensionality.
same here

2023-11-10 11:40 UTC, renetapopova commented on modules/ROOT/pages/reference/procedures.adoc
> +The toggle can pause or resume the secondary replication process
```suggestion
The toggle can pause or resume the secondary replication process.
```
And update the code base with the period.

2023-11-10 11:40 UTC, renetapopova commented on modules/ROOT/pages/reference/procedures.adoc
> +List capabilities
```suggestion
List capabilities.
```
Update the code as well.

2023-11-10 11:40 UTC, renetapopova commented on modules/ROOT/pages/reference/procedures.adoc
> +List the currently active config of Neo4j.
```suggestion
List the currently active configuration settings of Neo4j.
```
Also update the code base.

2023-11-10 11:40 UTC, renetapopova commented on modules/ROOT/pages/reference/procedures.adoc
> +Place a database into quarantine or remove from it.
```suggestion
Place a database into quarantine or remove it from it.
```
Fix it in the code base as well.

2023-11-10 11:40 UTC, renetapopova commented on modules/ROOT/pages/reference/procedures.adoc
> +Query JMX management data by domain and name. For instance, ":"
```suggestion
Query JMX management data by domain and name. For instance, use `:` to find all JMX beans.
```
Also in the code.

2023-11-10 11:40 UTC, renetapopova commented on modules/ROOT/pages/reference/procedures.adoc
> +With this method you can set the allocator, which is responsible to select servers for hosting databases.
```suggestion
With this method, you can set the allocator that is responsible for selecting servers for hosting databases.
```
also in the code

2023-11-10 11:40 UTC, renetapopova commented on modules/ROOT/pages/reference/procedures.adoc
> +Updates a given setting value.
Update in the code instead.

2023-11-13 13:19 UTC, NataliaIvakina commented on modules/ROOT/pages/reference/procedures.adoc
> +Query the given full-text index. Returns the matching nodes, and their Lucene query score, ordered by score.
```suggestion
```

2023-11-13 13:21 UTC, NataliaIvakina commented on modules/ROOT/pages/reference/procedures.adoc
> +Valid keys for the options map are: 'skip' to skip the top N results; 'limit' to limit the number of results returned; 'analyzer' to use the specified analyzer as search analyzer for this query.
```suggestion
```

2023-11-13 13:23 UTC, NataliaIvakina commented on modules/ROOT/pages/reference/procedures.adoc
> +Query the given full-text index. Returns the matching relationships, and their Lucene query score, ordered by score.
```suggestion
Query the given full-text index.

Returns the matching relationships and their Lucene query score, ordered by score.

Valid _key: value_ pairs for the `options` map are:

* `skip: <number>` -- skip the top N results.
* `limit: <number>` -- limit the number of results returned.
* `analyzer: <string>` -- use the specified analyzer as a search analyzer for this query.

The `options` map and any of the keys are optional.
An example of the `options` map: `{skip: 30, limit: 10, analyzer: 'whitespace'}`
```

2023-11-13 13:24 UTC, NataliaIvakina commented on modules/ROOT/pages/reference/procedures.adoc
> +Valid keys for the options map are: 'skip' to skip the top N results; 'limit' to limit the number of results returned; 'analyzer' to use the specified analyzer as search analyzer for this query.
```suggestion
```

2023-11-13 13:34 UTC, NataliaIvakina commented on modules/ROOT/pages/reference/procedures.adoc
> +Create a named node vector index for the given label and property for a specified vector dimensionality.
```suggestion
Create a named vector index for the given label, and property with given vector dimensionality, using the given similarity function.

`vectorDimension` must be between `1` and `2048` _inclusively_.

Valid case-insensitive values for the `vectorSimilarityFunction` are:

* `"euclidean"` -- Euclidean similarity, where:
+
image::euclidean_similarity_equation.svg["The Euclidean of vector v and vector u is defined as 1 over the quantity 1 plus the square of the l2-norm of vector v subtract vector u, which exists in the bounded set of real numbers between 0 exclusive and 1 inclusive."]
+

* `"cosine"` -- Cosine similarity, where:
+
image::cosine_similarity_equation.svg["The cosine of vector v and vector u is defined as half of the quanity 1 plus the scalar product of v hat u hat, which equals half of the quantity 1 plus the scalar product of vector v vector u over the product of the l2-norm of vector v and the l2 norm ov vector u, which exists in the bounded set of real numbers between 0 inclusive and 1 inclusive."]
In the above equation, the trigonometric cosine is given by the scalar product of the two unit vectors.
+
```

2023-11-13 13:34 UTC, NataliaIvakina commented on modules/ROOT/pages/reference/procedures.adoc
> +Valid similarity functions are 'EUCLIDEAN' and 'COSINE', and are case-insensitive.
```suggestion
```

2023-11-13 13:34 UTC, NataliaIvakina commented on modules/ROOT/pages/reference/procedures.adoc
> +Use the `db.index.vector.queryNodes` procedure to query the named index.
```suggestion
```

2023-11-13 14:13 UTC, renetapopova commented on modules/ROOT/pages/reference/procedures.adoc
> +An example of the `option
This sentence is missing its end.

2023-11-13 14:17 UTC, renetapopova commented on modules/ROOT/pages/reference/procedures.adoc
> +For example an endpoint may serve read queries, write queries and/or future `getRoutingTable` requests.
```suggestion
For example, an endpoint may serve read queries, write queries, and/or future `getRoutingTable` requests.
```

2023-11-14 11:24 UTC, NataliaIvakina commented on modules/ROOT/pages/reference/procedures.adoc
> +Updates a given setting value.
```suggestion
Update a given setting value.
Passing an empty value results in removing the configured value and falling back to the default value.
Changes do not persist and are lost if the server is restarted.
In a clustered environment, `dbms.setConfigValue` affects only the cluster member it is run against.
```

2023-11-14 11:25 UTC, NataliaIvakina commented on modules/ROOT/pages/reference/procedures.adoc
> +Changes will not persist and will be lost if the server is restarted.
```suggestion
```

2023-11-14 11:25 UTC, NataliaIvakina commented on modules/ROOT/pages/reference/procedures.adoc
> +Passing an empty value will result in removing the configured value and falling back to the default value.
```suggestion
```

2023-11-14 13:26 UTC, NataliaIvakina commented on modules/ROOT/pages/reference/procedures.adoc
> +An example of the `option
```suggestion
An example of the `options` map: `{skip: 30, limit: 10, analyzer: 'whitespace'}`
```

2023-11-15 13:07 UTC, merged