4.4 workload identity
neo4j/docs-operations pull request #1157
Opened 2023-10-24 17:41 UTC by renetapopova

Cherry-picks #1131 and updates the version and the yaml file.

2023-10-24 17:43 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates.

You can view the updated docs at https://neo4j-docs-operations-1157.surge.sh
<!-- Sticky Pull Request Comment -->

2023-10-25 11:21 UTC, harshitsinghvi22 requested changes

2023-10-25 11:21 UTC, harshitsinghvi22 commented on modules/ROOT/pages/kubernetes/operations/backup-restore.adoc
> +======
in 4.4 we dont have consistencyCheck attribute..this is the correct yaml

```
neo4j:
  image: "neo4j/helm-charts-backup"
  imageTag: "4.4.27"
  jobSchedule: "* * * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  backoffLimit: 3
backup:
  bucketName: "my-bucket"
  databaseAdminServiceName:  "standalone-admin" #This is the Neo4j Admin Service name.
  database: "neo4j,system"
  cloudProvider: "gcp"
  secretName: ""
  secretKeyName: ""

serviceAccountName: "demo-service-account"
```

2023-10-25 14:11 UTC, harshitsinghvi22 requested changes

2023-10-25 14:11 UTC, harshitsinghvi22 commented on modules/ROOT/pages/kubernetes/operations/backup-restore.adoc
> + checkConsistency: true
extra space needed before checkConsistency

2023-10-25 14:11 UTC, renetapopova commented on modules/ROOT/pages/kubernetes/operations/backup-restore.adoc
> + checkConsistency: true
ah, yes

2023-10-25 14:23 UTC, merged