remove the note about dropping the database
neo4j/docs-operations pull request #1454
Opened 2024-02-28 11:34 UTC by renetapopova

I removed the note but left the step 4. Do you think I should add the same step to the section **Restore a database backup**?

2024-02-28 11:37 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-operations-1454.surge.sh

Updated pages:
- [Restore a database backup](https://neo4j-docs-operations-1454.surge.sh/operations-manual/5/backup-restore/restore-backup)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-02-28 11:52 UTC, au-arena commented
>  Do you think I should add the same step to the section Restore a database backup?

No, I don't think so.

2024-02-28 11:52 UTC, au-arena approved these changes

2024-02-28 11:59 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-operations-1454.surge.sh

Updated pages:
- [Restore a database backup](https://neo4j-docs-operations-1454.surge.sh/operations-manual/5/backup-restore/restore-backup)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-02-28 13:28 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-operations-1454.surge.sh

Updated pages:
- [Restore a database backup](https://neo4j-docs-operations-1454.surge.sh/operations-manual/5/backup-restore/restore-backup)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-02-29 10:58 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-operations-1454.surge.sh

Updated pages:
- [Restore a database backup](https://neo4j-docs-operations-1454.surge.sh/operations-manual/5/backup-restore/restore-backup)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-02-29 11:19 UTC, au-arena requested changes

2024-02-29 11:20 UTC, renetapopova commented on modules/ROOT/pages/backup-restore/restore-backup.adoc
> +You should also skip the `CREATE DATABASE` step afterward.
ah, ok.

2024-02-29 11:31 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-operations-1454.surge.sh

Updated pages:
- [Restore a database backup](https://neo4j-docs-operations-1454.surge.sh/operations-manual/5/backup-restore/restore-backup)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-02-29 12:30 UTC, merged