Add a step for reseeding the cluster after migration
neo4j/docs-operations pull request #1488
Opened 2024-03-18 13:42 UTC by renetapopova

2024-03-18 13:45 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-operations-1488.surge.sh

Updated pages:
- [Store formats](https://neo4j-docs-operations-1488.surge.sh/operations-manual/5/database-internals/store-formats)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-03-18 13:54 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-operations-1488.surge.sh

Updated pages:
- [Store formats](https://neo4j-docs-operations-1488.surge.sh/operations-manual/5/database-internals/store-formats)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-03-20 11:47 UTC, neo-ionut requested changes

2024-03-20 12:16 UTC, renetapopova commented on modules/ROOT/pages/database-internals/store-formats.adoc
> +. If you are working with a cluster, re-seed the database after migration.
I'll update the steps.

2024-03-20 21:36 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-operations-1488.surge.sh

Updated pages:
- [Store formats](https://neo4j-docs-operations-1488.surge.sh/operations-manual/5/database-internals/store-formats)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-03-20 21:36 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-operations-1488.surge.sh

Updated pages:
- [Store formats](https://neo4j-docs-operations-1488.surge.sh/operations-manual/5/database-internals/store-formats)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-03-21 17:12 UTC, neo-ionut approved these changes
Very nice!

2024-03-22 11:12 UTC, merged