Add new configs for full-text indexes
neo4j/docs-operations pull request #1672
Opened 2024-06-12 11:12 UTC by NataliaIvakina

2024-06-12 11:14 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-operations-1672.surge.sh

Updated pages:
- [Configuration settings](https://neo4j-docs-operations-1672.surge.sh/operations-manual/5/configuration/configuration-settings)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-06-12 11:32 UTC, NataliaIvakina commented on modules/ROOT/pages/configuration/configuration-settings.adoc
> +[role=label-new--5.21]
```suggestion
[role=label--new-5.21]
```

2024-06-12 11:32 UTC, NataliaIvakina commented on modules/ROOT/pages/configuration/configuration-settings.adoc
> +[role=label-new--5.21]
```suggestion
[role=label--new-5.21]
```

2024-06-12 11:32 UTC, NataliaIvakina commented on modules/ROOT/pages/configuration/configuration-settings.adoc
> +[role=label-new--5.21]
```suggestion
[role=label--new-5.21]
```

2024-06-12 11:34 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-operations-1672.surge.sh

Updated pages:
- [Configuration settings](https://neo4j-docs-operations-1672.surge.sh/operations-manual/5/configuration/configuration-settings)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-06-12 12:23 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-operations-1672.surge.sh

Updated pages:
- [Configuration settings](https://neo4j-docs-operations-1672.surge.sh/operations-manual/5/configuration/configuration-settings)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-06-12 15:20 UTC, renetapopova commented on modules/ROOT/pages/configuration/configuration-settings.adoc
> +a|The number of threads that are applying the queued index updates for eventually consistent full-text indexes.
This also needs to be changed and merged in the codebase before the cut-off on Friday.

2024-06-12 15:28 UTC, renetapopova requested changes
Thanks, @NataliaIvakina. I added some comments to the descriptions. Just make sure the descriptions align with the ones in the codebase.

2024-06-12 15:28 UTC, renetapopova commented on modules/ROOT/pages/configuration/configuration-settings.adoc
> +a|How often an eventually consistent full-text index will be refreshed (readers guaranteed to see changes). If set to `0` then refresh is done by the threads applying eventually consistent fulltext i
```suggestion
a|How often an eventually consistent full-text index is refreshed (readers are guaranteed to see changes). If set to `0`, refresh is done by the threads applying eventually consistent full-text index updates.
```

(readers are guaranteed to see changes) sounds strange to me for a config description. Who are the readers?

2024-06-12 15:28 UTC, renetapopova commented on modules/ROOT/pages/configuration/configuration-settings.adoc
> +a|How often an eventually consistent full-text index will be refreshed (readers guaranteed to see changes). If set to `0` then refresh is done by the threads applying eventually consistent fulltext i
Same here - needs to be merged in the codebase before the cut-off.

2024-06-12 15:28 UTC, renetapopova commented on modules/ROOT/pages/configuration/configuration-settings.adoc
> +a|The number of threads that can do full-text index refresh in parallel, basically how many eventually consistent full-text indexes can be refreshed in parallel.
```suggestion
a|The number of threads that can do full-text index refresh in parallel, i.e. the number of eventually consistent full-text indexes that can be refreshed in parallel.
```

2024-06-12 15:28 UTC, renetapopova commented on modules/ROOT/pages/configuration/configuration-settings.adoc
> +a|The number of threads that can do full-text index refresh in parallel, basically how many eventually consistent full-text indexes can be refreshed in parallel.
Perhaps we can just use the second sentence.

Same here - needs to be merged in the codebase before the cut-off.

2024-06-13 08:03 UTC, NataliaIvakina commented on modules/ROOT/pages/configuration/configuration-settings.adoc
> +a|The number of threads that are applying the queued index updates for eventually consistent full-text indexes.
```suggestion
a|The number of threads that are applying to the queued index updates for eventually consistent full-text indexes.
```

2024-06-13 08:04 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-operations-1672.surge.sh

Updated pages:
- [Configuration settings](https://neo4j-docs-operations-1672.surge.sh/operations-manual/5/configuration/configuration-settings)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-06-13 08:06 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-operations-1672.surge.sh

Updated pages:
- [Configuration settings](https://neo4j-docs-operations-1672.surge.sh/operations-manual/5/configuration/configuration-settings)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-06-13 08:45 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-operations-1672.surge.sh

Updated pages:
- [Configuration settings](https://neo4j-docs-operations-1672.surge.sh/operations-manual/5/configuration/configuration-settings)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-06-13 08:46 UTC, NataliaIvakina commented on modules/ROOT/pages/configuration/configuration-settings.adoc
> +a|How often an eventually consistent full-text index is refreshed (readers are guaranteed to see changes). If set to `0`, refresh is done by the threads applying eventually consistent full-text index
readers or secondaries?

2024-06-13 10:08 UTC, renetapopova approved these changes
If it is aligned with codebase, I approve it. Otherwise, we need to keep the same descriptions as the ones there.

2024-06-13 13:30 UTC, NataliaIvakina commented on modules/ROOT/pages/configuration/configuration-settings.adoc
> +a|How often an eventually consistent full-text index is refreshed (readers are guaranteed to see changes). If set to `0`, refresh is done by the threads applying eventually consistent full-text index
```suggestion
a|How often an eventually consistent full-text index is refreshed (changes are guaranteed to be visible). If set to `0`, refresh is done by the threads applying eventually consistent full-text index updates.
```

2024-06-13 13:33 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-operations-1672.surge.sh

Updated pages:
- [Configuration settings](https://neo4j-docs-operations-1672.surge.sh/operations-manual/5/configuration/configuration-settings)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-06-13 13:47 UTC, merged