Adding new limited allocation procedures
neo4j/docs-operations pull request #1697
Opened 2024-06-27 11:01 UTC by yirensum

In this PR, we want to add documentation for the following cluster procedures:

```
dbms.cluster.deallocateDatabase(server, database)
dbms.cluster.deallocateNumberOfDatabases(server, number)
dbms.cluster.deallocateDatabaseFromServers(servers, database)
dbms.cluster.reallocateDatabase(database)
dbms.cluster.reallocateNumberOfDatabases(number)
```

We also add some scenarios in which a user might use these new procedures for

2024-06-27 11:03 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-operations-1697.surge.sh

Updated pages:
- [Managing databases in a cluster](https://neo4j-docs-operations-1697.surge.sh/operations-manual/5/clustering/databases)
- [Error handling](https://neo4j-docs-operations-1697.surge.sh/operations-manual/5/database-administration/standard-databases/errors)
- [Procedures](https://neo4j-docs-operations-1697.surge.sh/operations-manual/5/reference/procedures)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-06-27 14:00 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-operations-1697.surge.sh

Updated pages:
- [Managing databases in a cluster](https://neo4j-docs-operations-1697.surge.sh/operations-manual/5/clustering/databases)
- [Error handling](https://neo4j-docs-operations-1697.surge.sh/operations-manual/5/database-administration/standard-databases/errors)
- [Procedures](https://neo4j-docs-operations-1697.surge.sh/operations-manual/5/reference/procedures)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-06-27 14:53 UTC, renetapopova requested changes
I added some comments and suggestions. I am happy to address them myself when we agree that they will no longer be internal.

2024-06-27 14:53 UTC, renetapopova commented on modules/ROOT/pages/clustering/databases.adoc
>  == Reallocate databases
I think these two sections might be more readable if merged into one.

2024-06-27 14:53 UTC, renetapopova commented on modules/ROOT/pages/database-administration/standard-databases/errors.adoc
> +Alternatively, imagine if we added three new servers and want to reallocate a limited number of databases around the servers to rebalance.
Same here, I think it'll be better to have all methods for reallocation in one section.

2024-06-27 14:53 UTC, renetapopova commented on modules/ROOT/pages/database-administration/standard-databases/errors.adoc
> +[NOTE]
We don't need this note if we have the label above.

2024-06-27 14:53 UTC, renetapopova commented on modules/ROOT/pages/reference/procedures.adoc
> +.dbms.cluster.deallocateDatabase()
This procedure seems internal in the codebase `internal.dbms.cluster.deallocateDatabase`. Is this correct?

2024-06-27 14:53 UTC, renetapopova commented on modules/ROOT/pages/reference/procedures.adoc
> +.dbms.cluster.deallocateDatabaseFromServers()
same here

2024-06-27 14:53 UTC, renetapopova commented on modules/ROOT/pages/reference/procedures.adoc
> +.dbms.cluster.deallocateNumberOfDatabases()
same here

2024-06-27 14:53 UTC, renetapopova commented on modules/ROOT/pages/reference/procedures.adoc
> +.dbms.cluster.reallocateDatabase()
same here

2024-06-27 14:53 UTC, renetapopova commented on modules/ROOT/pages/reference/procedures.adoc
> +.dbms.cluster.reallocateNumberOfDatabases()
and here

2024-06-28 09:20 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-operations-1697.surge.sh

Updated pages:
- [Managing databases in a cluster](https://neo4j-docs-operations-1697.surge.sh/operations-manual/5/clustering/databases)
- [Error handling](https://neo4j-docs-operations-1697.surge.sh/operations-manual/5/database-administration/standard-databases/errors)
- [Procedures](https://neo4j-docs-operations-1697.surge.sh/operations-manual/5/reference/procedures)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-06-28 09:52 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-operations-1697.surge.sh

Updated pages:
- [Managing databases in a cluster](https://neo4j-docs-operations-1697.surge.sh/operations-manual/5/clustering/databases)
- [Error handling](https://neo4j-docs-operations-1697.surge.sh/operations-manual/5/database-administration/standard-databases/errors)
- [Procedures](https://neo4j-docs-operations-1697.surge.sh/operations-manual/5/reference/procedures)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-06-28 10:39 UTC, yirensum commented
Thanks for all the really good feedback @renetapopova, just having some discussions with PM about these changes - so on pause for maybe a day or two, will let you know when it's ready for re-review. Have a good weekend :)

2024-07-31 12:13 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-operations-1697.surge.sh

Updated pages:
- [Managing databases in a cluster](https://neo4j-docs-operations-1697.surge.sh/operations-manual/5/clustering/databases)
- [Procedures](https://neo4j-docs-operations-1697.surge.sh/operations-manual/5/reference/procedures)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-07-31 13:14 UTC, nick-giles-neo commented
These procedures should not be listed as 'admin only', they have recently had RBAC added to require `SERVER MANAGEMENT` instead. See https://github.com/neo4j/docs-operations/pull/1748 for what is being done for some procedures that will be admin _or_ 'server management'.

2024-08-05 13:44 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-operations-1697.surge.sh

Updated pages:
- [Managing databases in a cluster](https://neo4j-docs-operations-1697.surge.sh/operations-manual/5/clustering/databases)
- [Procedures](https://neo4j-docs-operations-1697.surge.sh/operations-manual/5/reference/procedures)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-08-05 14:14 UTC, NataliaIvakina commented on modules/ROOT/pages/reference/procedures.adoc
> +| label:admin-only[]
```suggestion
| label:new[Introduced in 5.23]
```

2024-08-05 14:14 UTC, NataliaIvakina commented on modules/ROOT/pages/reference/procedures.adoc
> +[role=label--enterprise-edition label--admin-only]
```suggestion
[role=label--enterprise-edition label--new-5.23]
```

2024-08-05 14:14 UTC, NataliaIvakina commented on modules/ROOT/pages/reference/procedures.adoc
> +[role=label--enterprise-edition label--admin-only]
```suggestion
[role=label--enterprise-edition label--new-5.23]
```

2024-08-05 14:14 UTC, NataliaIvakina commented on modules/ROOT/pages/reference/procedures.adoc
> +[role=label--enterprise-edition label--admin-only]
```suggestion
[role=label--enterprise-edition label--new-5.23]
```

2024-08-05 14:15 UTC, NataliaIvakina commented
my comments are based on the test

2024-08-05 18:17 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-operations-1697.surge.sh

Updated pages:
- [Managing databases in a cluster](https://neo4j-docs-operations-1697.surge.sh/operations-manual/5/clustering/databases)
- [Procedures](https://neo4j-docs-operations-1697.surge.sh/operations-manual/5/reference/procedures)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-08-05 18:38 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-operations-1697.surge.sh

Updated pages:
- [Managing databases in a cluster](https://neo4j-docs-operations-1697.surge.sh/operations-manual/5/clustering/databases)
- [Procedures](https://neo4j-docs-operations-1697.surge.sh/operations-manual/5/reference/procedures)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-08-05 18:45 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-operations-1697.surge.sh

Updated pages:
- [Managing databases in a cluster](https://neo4j-docs-operations-1697.surge.sh/operations-manual/5/clustering/databases)
- [Procedures](https://neo4j-docs-operations-1697.surge.sh/operations-manual/5/reference/procedures)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-08-05 18:49 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-operations-1697.surge.sh

Updated pages:
- [Managing databases in a cluster](https://neo4j-docs-operations-1697.surge.sh/operations-manual/5/clustering/databases)
- [Procedures](https://neo4j-docs-operations-1697.surge.sh/operations-manual/5/reference/procedures)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-08-05 18:55 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-operations-1697.surge.sh

Updated pages:
- [Managing databases in a cluster](https://neo4j-docs-operations-1697.surge.sh/operations-manual/5/clustering/databases)
- [Procedures](https://neo4j-docs-operations-1697.surge.sh/operations-manual/5/reference/procedures)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-08-05 18:58 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-operations-1697.surge.sh

Updated pages:
- [Managing databases in a cluster](https://neo4j-docs-operations-1697.surge.sh/operations-manual/5/clustering/databases)
- [Procedures](https://neo4j-docs-operations-1697.surge.sh/operations-manual/5/reference/procedures)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-08-05 19:02 UTC, renetapopova commented
The failing test is fixed in #1755.

2024-08-05 19:03 UTC, renetapopova reviewed
Hey @yirensum, I think this PR is ready for a technical review.

2024-08-05 19:07 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-operations-1697.surge.sh

Updated pages:
- [Managing databases in a cluster](https://neo4j-docs-operations-1697.surge.sh/operations-manual/5/clustering/databases)
- [Procedures](https://neo4j-docs-operations-1697.surge.sh/operations-manual/5/reference/procedures)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-08-06 09:53 UTC, yirensum reviewed
Looks great! I've tested the instructions on my machine as well, good to merge

2024-08-06 12:04 UTC, renetapopova commented on modules/ROOT/pages/clustering/databases.adoc
> +* xref:reference/procedures.adoc#procedure_dbms_cluster_deallocateDatabaseFromServers[`dbms.cluster.deallocateDatabaseFromServers(["server-name1", "server-name2"], "database-name")`]
Ah, good catch!

2024-08-06 14:17 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-operations-1697.surge.sh

Updated pages:
- [Managing databases in a cluster](https://neo4j-docs-operations-1697.surge.sh/operations-manual/5/clustering/databases)
- [Procedures](https://neo4j-docs-operations-1697.surge.sh/operations-manual/5/reference/procedures)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-08-06 14:52 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-operations-1697.surge.sh

Updated pages:
- [Managing databases in a cluster](https://neo4j-docs-operations-1697.surge.sh/operations-manual/5/clustering/databases)
- [Procedures](https://neo4j-docs-operations-1697.surge.sh/operations-manual/5/reference/procedures)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-08-07 09:13 UTC, NataliaIvakina approved these changes
Looks good!

2024-08-07 09:19 UTC, yirensum commented
Thanks! I've pushed a fix for the showParallelDiscoveryState, sorry forgot to change it in my previous PR, should go green now

2024-08-07 09:29 UTC, yirensum commented
Could I get a ✅ from you as well @renetapopova, thank you!

2024-08-07 10:08 UTC, renetapopova approved these changes

2024-08-07 10:09 UTC, merged