Update the first page of the Clustering section
neo4j/docs-operations pull request #1747
Opened 2024-07-26 12:43 UTC by NataliaIvakina

2024-07-26 12:45 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-operations-1747.surge.sh

Updated pages:
- [Clustering](https://neo4j-docs-operations-1747.surge.sh/operations-manual/5/clustering)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-07-29 14:04 UTC, renetapopova requested changes
Thanks, @NataliaIvakina! As I wrote here as a comment, I think we need to align the titles in the navigation and on the pages and reflect that here as well. Otherwise, the clustering section is inconsistent with the rest of the manual and also within itself. What do you think?

2024-07-29 14:04 UTC, renetapopova commented on modules/ROOT/pages/clustering/index.adoc
> +** xref:clustering/clustering-advanced/reconciler.adoc[Reconciler] -- An internal component which observes the requested state of a server and makes changes to the server to match that state.
```suggestion
** xref:clustering/clustering-advanced/reconciler.adoc[Reconciler] -- An internal component that observes the requested state of a server and makes changes to the server to match that state. 
```

2024-07-29 14:04 UTC, renetapopova commented on modules/ROOT/pages/clustering/index.adoc
>  * xref:clustering/glossary.adoc[Clustering glossary] -- A glossary of terms used in the clustering documentation.
```suggestion
* xref:clustering/glossary.adoc[Clustering glossary] -- A glossary of terms related to the Neo4j clustering.
```

2024-07-29 14:37 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-operations-1747.surge.sh

Updated pages:
- [Clustering](https://neo4j-docs-operations-1747.surge.sh/operations-manual/5/clustering)
- [Leadership, routing, and load balancing](https://neo4j-docs-operations-1747.surge.sh/operations-manual/5/clustering/setup/routing)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-07-29 14:39 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-operations-1747.surge.sh

Updated pages:
- [Clustering](https://neo4j-docs-operations-1747.surge.sh/operations-manual/5/clustering)
- [Leadership, routing, and load balancing](https://neo4j-docs-operations-1747.surge.sh/operations-manual/5/clustering/setup/routing)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-08-01 09:55 UTC, renetapopova approved these changes
Looks good now. Thanks!

2024-08-01 12:52 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-operations-1747.surge.sh

Updated pages:
- [Advanced clustering](https://neo4j-docs-operations-1747.surge.sh/operations-manual/5/clustering/clustering-advanced)
- [Clustering](https://neo4j-docs-operations-1747.surge.sh/operations-manual/5/clustering)
- [Leadership, routing, and load balancing](https://neo4j-docs-operations-1747.surge.sh/operations-manual/5/clustering/setup/routing)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-08-01 12:53 UTC, NataliaIvakina commented
we can't remove the _index.adoc_ file from the Advanced clustering section, because it's tied up to the Advanced causal clustering section in 4.4

2024-08-01 12:53 UTC, merged