Deprecate `existingDataSeedInstance` option to CREATE DATABASE
neo4j/docs-operations pull request #1821
Opened 2024-09-19 16:00 UTC by mnd999

Replace with new option `existingDataSeedServer`

2024-09-19 16:02 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-operations-1821.surge.sh

Updated pages:
- [Managing databases in a cluster](https://neo4j-docs-operations-1821.surge.sh/operations-manual/5/clustering/databases)
- [Create, start, and stop databases](https://neo4j-docs-operations-1821.surge.sh/operations-manual/5/database-administration/standard-databases/create-databases)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-09-20 09:02 UTC, HannesSandberg requested changes

2024-09-20 09:02 UTC, HannesSandberg commented on modules/ROOT/pages/database-administration/standard-databases/create-databases.adoc
> +Currently, this is only supported with `existingDataSeedInstance`, `existingDataSeedServer` and `seedURI`, and must be set to `use`, which indicates the existing data files should be used for the new
I can not make a comment above. But we should mention `existingDataSeedServer` on row 34 as well.

2024-09-20 14:53 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-operations-1821.surge.sh

Updated pages:
- [Managing databases in a cluster](https://neo4j-docs-operations-1821.surge.sh/operations-manual/5/clustering/databases)
- [Create, start, and stop databases](https://neo4j-docs-operations-1821.surge.sh/operations-manual/5/database-administration/standard-databases/create-databases)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-09-23 06:39 UTC, HannesSandberg approved these changes

2024-09-30 14:21 UTC, renetapopova approved these changes
Thanks, @mnd999. It looks good; I have just two minor suggestions.

2024-09-30 14:21 UTC, renetapopova commented on modules/ROOT/pages/database-administration/standard-databases/create-databases.adoc
> +The server ID can be found in the `serverId` column after running `SHOW SERVERS`. `existingDataSeedInstance` was replaced by `existingDataSeedServer` in Neo4j 5.25.
```suggestion
The server ID can be found in the `serverId` column after running `SHOW SERVERS`. 
`existingDataSeedInstance` is replaced by `existingDataSeedServer` in Neo4j 5.25.
```

2024-09-30 14:21 UTC, renetapopova commented on modules/ROOT/pages/database-administration/standard-databases/create-databases.adoc
> +If the store is seeded with `seedURI`, `existingDataSeedInstance` or `existingDataSeedServer`, or if the command is being used to mount pre-existing store files already present on the disk, they will
```suggestion
If the store is seeded with `seedURI`, `existingDataSeedInstance` or `existingDataSeedServer`, or if the command is used to mount pre-existing store files already present on the disk, they will retain their current store format without any modifications.
```

2024-10-09 10:14 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-operations-1821.surge.sh

Updated pages:
- [Managing databases in a cluster](https://neo4j-docs-operations-1821.surge.sh/operations-manual/5/clustering/databases)
- [Create, start, and stop databases](https://neo4j-docs-operations-1821.surge.sh/operations-manual/5/database-administration/standard-databases/create-databases)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-10-09 10:17 UTC, merged