Configure LDAP password through secret
neo4j/docs-operations pull request #658
Opened 2023-04-11 12:39 UTC by renetapopova

Hey @harshitsinghvi22, the other lines (not related to this PR) were added to the yaml file when I pasted the new version from the helm chart repo. They seemed to be missing in the doc's version.

2023-04-11 12:41 UTC, neo-technology-commit-status-publisher commented
Looks like you've updated the documentation!

Check out your changes at https://neo4j-docs-operations-658.surge.sh
<!-- Sticky Pull Request Comment -->

2023-04-11 14:52 UTC, harshitsinghvi22 requested changes

2023-04-11 14:52 UTC, harshitsinghvi22 commented on modules/ROOT/pages/kubernetes/configuration.adoc
> +To configure the Neo4j Helm deployment to use the LDAP system password through secret, you need to create a Kubernetes secret with the LDAP password and then add the secret name and the mount path to
please mention the secret MUST have a key called LDAP_PASS

2023-04-12 13:42 UTC, harshitsinghvi22 approved these changes

2023-04-20 09:24 UTC, merged