New information about disk monitoring
neo4j/docs-operations pull request #662
Opened 2023-04-12 10:33 UTC by lidiazuin

2023-04-12 10:35 UTC, neo-technology-commit-status-publisher commented
Looks like you've updated the documentation!

Check out your changes at https://neo4j-docs-operations-662.surge.sh
<!-- Sticky Pull Request Comment -->

2023-04-12 13:53 UTC, renetapopova requested changes
Thanks, @lidiazuin, for looking into this. I left a comment.

2023-04-12 13:53 UTC, renetapopova commented on modules/ROOT/pages/monitoring/metrics/expose.adoc
> +== Disks
This should be incorporated into the Essential Metrics page here - https://neo4j-docs-operations-662.surge.sh/operations-manual/5/monitoring/metrics/essential/#_server_load_metrics, not to Expose, as in the Expose metrics, we only list the different options on how the metrics can be exposed.

2023-04-14 09:35 UTC, renetapopova requested changes
Thanks, @lidiazuin! I added some comments, and you also need to add the link to https://neo4j.com/docs/operations-manual/current/clustering/monitoring/endpoints/[Monitor cluster endpoints for status information] at line 113.

2023-04-14 09:35 UTC, renetapopova commented on modules/ROOT/pages/monitoring/metrics/expose.adoc
> +* Graphite -- send metrics to https://graphiteapp.org/[Graphite] or any monitoring tool based on the Graphite protocol (`disabled` by default).
```suggestion
* Graphite -- send metrics to https://graphiteapp.org/[Graphite] or any monitoring tool based on the Graphite protocol. Disabled by default.
```

2023-04-14 09:35 UTC, renetapopova commented on modules/ROOT/pages/monitoring/metrics/essential.adoc
> +See more recommendations about xref:performance/disks-ram-and-other-tips.adoc#performance-storage[system storage practices] and xref:clustering/monitoring/show-servers-monitoring.adoc[monitoring serv
```suggestion
For more recommendations, see xref:performance/disks-ram-and-other-tips.adoc#performance-storage[Disks, RAM and other tips], as well as xref:clustering/monitoring/show-servers-monitoring.adoc[Monitoring servers] and xref:clustering/monitoring/show-databases-monitoring.adoc[Monitoring databases] in a Neo4j cluster.
```

2023-04-17 12:58 UTC, renetapopova approved these changes
Approved ✅

2023-04-17 13:01 UTC, merged