Updating description of neo4j-import data command after incremental import implementation
neo4j/docs-operations pull request #664
Opened 2023-04-12 14:20 UTC by lidiazuin

2023-04-12 14:22 UTC, neo-technology-commit-status-publisher commented
Looks like you've updated the documentation!

Check out your changes at https://neo4j-docs-operations-664.surge.sh
<!-- Sticky Pull Request Comment -->

2023-04-12 14:33 UTC, renetapopova requested changes
Thanks, @lidiazuin. I left a suggestion. With the introduction of incremental import, the command can also be used to import data into an existing database.

2023-04-13 09:18 UTC, renetapopova approved these changes
Looks good now! Just a small comment. Thank you!

2023-04-13 09:18 UTC, renetapopova commented on modules/ROOT/pages/tutorial/neo4j-admin-import.adoc
> +It is used for loading large amounts of data from CSV files and supports full and incremental import into a running or stopped Neo4j DBMS.
"It" refers to "tutorial". I would suggest:
```suggestion
The import command is used for loading large amounts of data from CSV files and supports full and incremental import into a running or stopped Neo4j DBMS.
```

2023-04-13 09:38 UTC, merged