Remove port-forward and the enterprise label from lb
neo4j/docs-operations pull request #748
Opened 2023-04-26 12:25 UTC by renetapopova

2023-04-26 12:26 UTC, renetapopova commented on modules/ROOT/pages/kubernetes/quickstart-standalone/verify-installation.adoc
> +TODO
@harshitsinghvi22, could you please provide me with an example output? Thanks!

2023-04-26 12:27 UTC, neo-technology-commit-status-publisher commented
Looks like you've updated the documentation!

Check out your changes at https://neo4j-docs-operations-748.surge.sh
<!-- Sticky Pull Request Comment -->

2023-04-26 15:31 UTC, harshitsinghvi22 requested changes

2023-04-26 15:31 UTC, harshitsinghvi22 commented on modules/ROOT/pages/kubernetes/quickstart-standalone/verify-installation.adoc
> +. Use the IP address of the external IP of the `LoadBalancer` to access Neo4j from an application outside the Kubernetes cluster.
we can just say here.. Use the external IP of the LoadBalancer

2023-04-27 19:01 UTC, harshitsinghvi22 approved these changes

2023-04-27 19:02 UTC, merged