Update ssl-framework.adoc
neo4j/docs-operations pull request #778
Opened 2023-05-12 10:17 UTC by ali-ince

I think we should mention to include the certificate chain in the `public.crt` file for clients to be able to verify them properly.

2023-05-12 10:19 UTC, neo-technology-commit-status-publisher commented
Looks like you've updated the documentation!

Check out your changes at https://neo4j-docs-operations-778.surge.sh
<!-- Sticky Pull Request Comment -->

2023-05-12 15:28 UTC, renetapopova requested changes
Thanks, @ali-ince! I have an editorial suggestion just to improve the wording.

2023-05-12 15:28 UTC, renetapopova commented on modules/ROOT/pages/security/ssl-framework.adoc
>  The instructions on this page assume that you have already obtained the required certificates from the CA.
```suggestion
The instructions on this page assume that you have already obtained the required certificates from the CA and added them to the _public.crt_ file.
To achieve this, you should concatenate each PEM-encoded certificate, starting from the leaf certificate and moving up the chain toward the root.
```

2023-05-12 15:28 UTC, renetapopova commented on modules/ROOT/pages/security/ssl-framework.adoc
> +Be sure to include the certificate chain used by your CA to be included in the `public.crt` file, by concatenating each `PEM-encoded` certificate in the `public.crt` file starting from the leaf certi
```suggestion
```

2023-05-16 14:09 UTC, renetapopova approved these changes

2023-05-16 14:12 UTC, merged