Invalid NEO4J_PLUGINS values now produces a helpful error message
neo4j/docs-operations pull request #793
Opened 2023-05-17 10:48 UTC by renetapopova

2023-05-17 10:49 UTC, neo-technology-commit-status-publisher commented
Looks like you've updated the documentation!

Check out your changes at https://neo4j-docs-operations-793.surge.sh
<!-- Sticky Pull Request Comment -->

2023-05-22 10:06 UTC, jennyowen requested changes
This is mostly fine, there's just an incorrect statement about needing to use the `--user` flag to be deleted and some minor code cleanup.

2023-05-22 10:06 UTC, jennyowen commented on modules/ROOT/pages/docker/operations.adoc
> +====
this is not true, you can delete the `--user="$(id -u):$(id -g)"` from all the examples and they should still work.

2023-05-23 07:45 UTC, jennyowen commented on modules/ROOT/pages/docker/operations.adoc
> +====
yes I think it's a good idea to remove the line from the examples.

2023-05-23 08:46 UTC, jennyowen approved these changes
wonderful!

2023-05-23 10:22 UTC, merged